// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addons.sql

package sqlcgen

import (
	"context"
	"time"
)

const addAddonOwner = `-- name: AddAddonOwner :exec
INSERT INTO addon_owners (addon_id, user_id) VALUES (?, ?)
`

type AddAddonOwnerParams struct {
	AddonID int64 `json:"addon_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) AddAddonOwner(ctx context.Context, arg AddAddonOwnerParams) error {
	_, err := q.db.ExecContext(ctx, addAddonOwner, arg.AddonID, arg.UserID)
	return err
}

const createAddon = `-- name: CreateAddon :one
INSERT INTO addons (name, engine, version, cpu_limit, memory_limit_mb, password, status, created_at)
VALUES (?, ?, ?, ?, ?, ?, 'provisioning', ?)
RETURNING id, name, engine, version, cpu_limit, memory_limit_mb, password, status, container_name, created_at, deleted_at, exposed, host_port
`

type CreateAddonParams struct {
	Name          string    `json:"name"`
	Engine        string    `json:"engine"`
	Version       string    `json:"version"`
	CpuLimit      float64   `json:"cpu_limit"`
	MemoryLimitMb int64     `json:"memory_limit_mb"`
	Password      string    `json:"password"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) CreateAddon(ctx context.Context, arg CreateAddonParams) (Addon, error) {
	row := q.db.QueryRowContext(ctx, createAddon,
		arg.Name,
		arg.Engine,
		arg.Version,
		arg.CpuLimit,
		arg.MemoryLimitMb,
		arg.Password,
		arg.CreatedAt,
	)
	var i Addon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.Password,
		&i.Status,
		&i.ContainerName,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Exposed,
		&i.HostPort,
	)
	return i, err
}

const getAddonByID = `-- name: GetAddonByID :one
SELECT id, name, engine, version, cpu_limit, memory_limit_mb, password, status, container_name, created_at, deleted_at, exposed, host_port FROM addons WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetAddonByID(ctx context.Context, id int64) (Addon, error) {
	row := q.db.QueryRowContext(ctx, getAddonByID, id)
	var i Addon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.Password,
		&i.Status,
		&i.ContainerName,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Exposed,
		&i.HostPort,
	)
	return i, err
}

const getAddonByName = `-- name: GetAddonByName :one
SELECT id, name, engine, version, cpu_limit, memory_limit_mb, password, status, container_name, created_at, deleted_at, exposed, host_port FROM addons WHERE name = ? AND deleted_at IS NULL
`

func (q *Queries) GetAddonByName(ctx context.Context, name string) (Addon, error) {
	row := q.db.QueryRowContext(ctx, getAddonByName, name)
	var i Addon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.Password,
		&i.Status,
		&i.ContainerName,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Exposed,
		&i.HostPort,
	)
	return i, err
}

const isAddonOwner = `-- name: IsAddonOwner :one
SELECT EXISTS(SELECT 1 FROM addon_owners WHERE addon_id = ? AND user_id = ?) AS is_owner
`

type IsAddonOwnerParams struct {
	AddonID int64 `json:"addon_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) IsAddonOwner(ctx context.Context, arg IsAddonOwnerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAddonOwner, arg.AddonID, arg.UserID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const listAddonOwners = `-- name: ListAddonOwners :many
SELECT u.id, u.username, u.is_admin, u.created_at, u.deleted_at FROM users u
  INNER JOIN addon_owners o ON o.user_id = u.id
  WHERE o.addon_id = ? AND u.deleted_at IS NULL ORDER BY u.id
`

func (q *Queries) ListAddonOwners(ctx context.Context, addonID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAddonOwners, addonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAddons = `-- name: ListAddons :many
SELECT id, name, engine, version, cpu_limit, memory_limit_mb, password, status, container_name, created_at, deleted_at, exposed, host_port FROM addons WHERE deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListAddons(ctx context.Context) ([]Addon, error) {
	rows, err := q.db.QueryContext(ctx, listAddons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Addon
	for rows.Next() {
		var i Addon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.Password,
			&i.Status,
			&i.ContainerName,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Exposed,
			&i.HostPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAddonsByOwner = `-- name: ListAddonsByOwner :many
SELECT s.id, s.name, s.engine, s.version, s.cpu_limit, s.memory_limit_mb, s.password, s.status, s.container_name, s.created_at, s.deleted_at, s.exposed, s.host_port FROM addons s
  INNER JOIN addon_owners o ON o.addon_id = s.id
  WHERE o.user_id = ? AND s.deleted_at IS NULL
  ORDER BY s.id
`

func (q *Queries) ListAddonsByOwner(ctx context.Context, userID int64) ([]Addon, error) {
	rows, err := q.db.QueryContext(ctx, listAddonsByOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Addon
	for rows.Next() {
		var i Addon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.Password,
			&i.Status,
			&i.ContainerName,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Exposed,
			&i.HostPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInflightAddons = `-- name: ListInflightAddons :many
SELECT id, name, engine, version, cpu_limit, memory_limit_mb, password, status, container_name, created_at, deleted_at, exposed, host_port FROM addons WHERE status = 'provisioning' AND deleted_at IS NULL
`

func (q *Queries) ListInflightAddons(ctx context.Context) ([]Addon, error) {
	rows, err := q.db.QueryContext(ctx, listInflightAddons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Addon
	for rows.Next() {
		var i Addon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.Password,
			&i.Status,
			&i.ContainerName,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Exposed,
			&i.HostPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAddonOwner = `-- name: RemoveAddonOwner :exec
DELETE FROM addon_owners WHERE addon_id = ? AND user_id = ?
`

type RemoveAddonOwnerParams struct {
	AddonID int64 `json:"addon_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) RemoveAddonOwner(ctx context.Context, arg RemoveAddonOwnerParams) error {
	_, err := q.db.ExecContext(ctx, removeAddonOwner, arg.AddonID, arg.UserID)
	return err
}

const setAddonExposed = `-- name: SetAddonExposed :exec
UPDATE addons SET exposed = ? WHERE id = ?
`

type SetAddonExposedParams struct {
	Exposed bool  `json:"exposed"`
	ID      int64 `json:"id"`
}

func (q *Queries) SetAddonExposed(ctx context.Context, arg SetAddonExposedParams) error {
	_, err := q.db.ExecContext(ctx, setAddonExposed, arg.Exposed, arg.ID)
	return err
}

const setAddonHostPort = `-- name: SetAddonHostPort :exec
UPDATE addons SET host_port = ? WHERE id = ?
`

type SetAddonHostPortParams struct {
	HostPort int64 `json:"host_port"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetAddonHostPort(ctx context.Context, arg SetAddonHostPortParams) error {
	_, err := q.db.ExecContext(ctx, setAddonHostPort, arg.HostPort, arg.ID)
	return err
}

const softDeleteAddon = `-- name: SoftDeleteAddon :exec
UPDATE addons SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteAddonParams struct {
	DeletedAt *time.Time `json:"deleted_at"`
	ID        int64      `json:"id"`
}

func (q *Queries) SoftDeleteAddon(ctx context.Context, arg SoftDeleteAddonParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteAddon, arg.DeletedAt, arg.ID)
	return err
}

const updateAddonStatus = `-- name: UpdateAddonStatus :exec
UPDATE addons SET status = ?, container_name = ? WHERE id = ?
`

type UpdateAddonStatusParams struct {
	Status        string  `json:"status"`
	ContainerName *string `json:"container_name"`
	ID            int64   `json:"id"`
}

func (q *Queries) UpdateAddonStatus(ctx context.Context, arg UpdateAddonStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAddonStatus, arg.Status, arg.ContainerName, arg.ID)
	return err
}
