// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package sqlcgen

import (
	"context"
	"time"
)

const addOwner = `-- name: AddOwner :exec
INSERT INTO app_owners (app_id, user_id) VALUES (?, ?)
`

type AddOwnerParams struct {
	AppID  int64 `json:"app_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddOwner(ctx context.Context, arg AddOwnerParams) error {
	_, err := q.db.ExecContext(ctx, addOwner, arg.AppID, arg.UserID)
	return err
}

const createApp = `-- name: CreateApp :one
INSERT INTO apps (name, port, health_path, health_timeout_sec, cpu_limit, memory_limit_mb, volumes, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, port, health_path, health_timeout_sec, cpu_limit, memory_limit_mb, current_deploy_id, created_at, deleted_at, volumes
`

type CreateAppParams struct {
	Name             string    `json:"name"`
	Port             int64     `json:"port"`
	HealthPath       string    `json:"health_path"`
	HealthTimeoutSec int64     `json:"health_timeout_sec"`
	CpuLimit         float64   `json:"cpu_limit"`
	MemoryLimitMb    int64     `json:"memory_limit_mb"`
	Volumes          string    `json:"volumes"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, createApp,
		arg.Name,
		arg.Port,
		arg.HealthPath,
		arg.HealthTimeoutSec,
		arg.CpuLimit,
		arg.MemoryLimitMb,
		arg.Volumes,
		arg.CreatedAt,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Port,
		&i.HealthPath,
		&i.HealthTimeoutSec,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.CurrentDeployID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Volumes,
	)
	return i, err
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, name, port, health_path, health_timeout_sec, cpu_limit, memory_limit_mb, current_deploy_id, created_at, deleted_at, volumes FROM apps WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetAppByID(ctx context.Context, id int64) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Port,
		&i.HealthPath,
		&i.HealthTimeoutSec,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.CurrentDeployID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Volumes,
	)
	return i, err
}

const getAppByName = `-- name: GetAppByName :one
SELECT id, name, port, health_path, health_timeout_sec, cpu_limit, memory_limit_mb, current_deploy_id, created_at, deleted_at, volumes FROM apps WHERE name = ? AND deleted_at IS NULL
`

func (q *Queries) GetAppByName(ctx context.Context, name string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByName, name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Port,
		&i.HealthPath,
		&i.HealthTimeoutSec,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.CurrentDeployID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Volumes,
	)
	return i, err
}

const isOwner = `-- name: IsOwner :one
SELECT EXISTS(SELECT 1 FROM app_owners WHERE app_id = ? AND user_id = ?) AS is_owner
`

type IsOwnerParams struct {
	AppID  int64 `json:"app_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) IsOwner(ctx context.Context, arg IsOwnerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isOwner, arg.AppID, arg.UserID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const listApps = `-- name: ListApps :many
SELECT id, name, port, health_path, health_timeout_sec, cpu_limit, memory_limit_mb, current_deploy_id, created_at, deleted_at, volumes FROM apps WHERE deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Port,
			&i.HealthPath,
			&i.HealthTimeoutSec,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.CurrentDeployID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Volumes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByOwner = `-- name: ListAppsByOwner :many
SELECT a.id, a.name, a.port, a.health_path, a.health_timeout_sec, a.cpu_limit, a.memory_limit_mb, a.current_deploy_id, a.created_at, a.deleted_at, a.volumes FROM apps a
  INNER JOIN app_owners o ON o.app_id = a.id
  WHERE o.user_id = ? AND a.deleted_at IS NULL
  ORDER BY a.id
`

func (q *Queries) ListAppsByOwner(ctx context.Context, userID int64) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Port,
			&i.HealthPath,
			&i.HealthTimeoutSec,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.CurrentDeployID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Volumes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwners = `-- name: ListOwners :many
SELECT u.id, u.username, u.is_admin, u.created_at, u.deleted_at FROM users u
  INNER JOIN app_owners o ON o.user_id = u.id
  WHERE o.app_id = ? AND u.deleted_at IS NULL ORDER BY u.id
`

func (q *Queries) ListOwners(ctx context.Context, appID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listOwners, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOwner = `-- name: RemoveOwner :exec
DELETE FROM app_owners WHERE app_id = ? AND user_id = ?
`

type RemoveOwnerParams struct {
	AppID  int64 `json:"app_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RemoveOwner(ctx context.Context, arg RemoveOwnerParams) error {
	_, err := q.db.ExecContext(ctx, removeOwner, arg.AppID, arg.UserID)
	return err
}

const setCurrentDeploy = `-- name: SetCurrentDeploy :exec
UPDATE apps SET current_deploy_id = ? WHERE id = ?
`

type SetCurrentDeployParams struct {
	CurrentDeployID *int64 `json:"current_deploy_id"`
	ID              int64  `json:"id"`
}

func (q *Queries) SetCurrentDeploy(ctx context.Context, arg SetCurrentDeployParams) error {
	_, err := q.db.ExecContext(ctx, setCurrentDeploy, arg.CurrentDeployID, arg.ID)
	return err
}

const softDeleteApp = `-- name: SoftDeleteApp :exec
UPDATE apps SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteAppParams struct {
	DeletedAt *time.Time `json:"deleted_at"`
	ID        int64      `json:"id"`
}

func (q *Queries) SoftDeleteApp(ctx context.Context, arg SoftDeleteAppParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteApp, arg.DeletedAt, arg.ID)
	return err
}

const updateAppConfig = `-- name: UpdateAppConfig :exec
UPDATE apps SET port = ?, health_path = ?, health_timeout_sec = ?, cpu_limit = ?, memory_limit_mb = ?, volumes = ?
  WHERE id = ?
`

type UpdateAppConfigParams struct {
	Port             int64   `json:"port"`
	HealthPath       string  `json:"health_path"`
	HealthTimeoutSec int64   `json:"health_timeout_sec"`
	CpuLimit         float64 `json:"cpu_limit"`
	MemoryLimitMb    int64   `json:"memory_limit_mb"`
	Volumes          string  `json:"volumes"`
	ID               int64   `json:"id"`
}

func (q *Queries) UpdateAppConfig(ctx context.Context, arg UpdateAppConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateAppConfig,
		arg.Port,
		arg.HealthPath,
		arg.HealthTimeoutSec,
		arg.CpuLimit,
		arg.MemoryLimitMb,
		arg.Volumes,
		arg.ID,
	)
	return err
}
