// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package sqlcgen

import (
	"context"
	"time"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (app_id, image_digest, image_ref, commit_sha, ref, status, triggered_by, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, app_id, image_digest, image_ref, commit_sha, ref, status, failure_reason, triggered_by, container_name, created_at, finished_at
`

type CreateDeploymentParams struct {
	AppID       int64     `json:"app_id"`
	ImageDigest string    `json:"image_digest"`
	ImageRef    string    `json:"image_ref"`
	CommitSha   *string   `json:"commit_sha"`
	Ref         *string   `json:"ref"`
	Status      string    `json:"status"`
	TriggeredBy int64     `json:"triggered_by"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.AppID,
		arg.ImageDigest,
		arg.ImageRef,
		arg.CommitSha,
		arg.Ref,
		arg.Status,
		arg.TriggeredBy,
		arg.CreatedAt,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageDigest,
		&i.ImageRef,
		&i.CommitSha,
		&i.Ref,
		&i.Status,
		&i.FailureReason,
		&i.TriggeredBy,
		&i.ContainerName,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, app_id, image_digest, image_ref, commit_sha, ref, status, failure_reason, triggered_by, container_name, created_at, finished_at FROM deployments WHERE id = ?
`

func (q *Queries) GetDeployment(ctx context.Context, id int64) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ImageDigest,
		&i.ImageRef,
		&i.CommitSha,
		&i.Ref,
		&i.Status,
		&i.FailureReason,
		&i.TriggeredBy,
		&i.ContainerName,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listDeploymentsForApp = `-- name: ListDeploymentsForApp :many
SELECT id, app_id, image_digest, image_ref, commit_sha, ref, status, failure_reason, triggered_by, container_name, created_at, finished_at FROM deployments WHERE app_id = ? ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListDeploymentsForAppParams struct {
	AppID  int64 `json:"app_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDeploymentsForApp(ctx context.Context, arg ListDeploymentsForAppParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsForApp, arg.AppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ImageDigest,
			&i.ImageRef,
			&i.CommitSha,
			&i.Ref,
			&i.Status,
			&i.FailureReason,
			&i.TriggeredBy,
			&i.ContainerName,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInflightDeployments = `-- name: ListInflightDeployments :many
SELECT id, app_id, image_digest, image_ref, commit_sha, ref, status, failure_reason, triggered_by, container_name, created_at, finished_at FROM deployments WHERE status IN ('pending','deploying')
`

func (q *Queries) ListInflightDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listInflightDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ImageDigest,
			&i.ImageRef,
			&i.CommitSha,
			&i.Ref,
			&i.Status,
			&i.FailureReason,
			&i.TriggeredBy,
			&i.ContainerName,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments SET status = ?, failure_reason = ?, container_name = ?, finished_at = ?
  WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status        string     `json:"status"`
	FailureReason *string    `json:"failure_reason"`
	ContainerName *string    `json:"container_name"`
	FinishedAt    *time.Time `json:"finished_at"`
	ID            int64      `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus,
		arg.Status,
		arg.FailureReason,
		arg.ContainerName,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
