// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: env.sql

package sqlcgen

import (
	"context"
)

const deleteAllAppEnv = `-- name: DeleteAllAppEnv :exec
DELETE FROM app_env WHERE app_id = ?
`

func (q *Queries) DeleteAllAppEnv(ctx context.Context, appID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllAppEnv, appID)
	return err
}

const deleteAppEnvVar = `-- name: DeleteAppEnvVar :exec
DELETE FROM app_env WHERE app_id = ? AND key = ?
`

type DeleteAppEnvVarParams struct {
	AppID int64  `json:"app_id"`
	Key   string `json:"key"`
}

func (q *Queries) DeleteAppEnvVar(ctx context.Context, arg DeleteAppEnvVarParams) error {
	_, err := q.db.ExecContext(ctx, deleteAppEnvVar, arg.AppID, arg.Key)
	return err
}

const getAppEnv = `-- name: GetAppEnv :many
SELECT key, value FROM app_env WHERE app_id = ? ORDER BY key
`

type GetAppEnvRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetAppEnv(ctx context.Context, appID int64) ([]GetAppEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, getAppEnv, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAppEnvRow
	for rows.Next() {
		var i GetAppEnvRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppEnvVar = `-- name: SetAppEnvVar :exec
INSERT INTO app_env (app_id, key, value) VALUES (?, ?, ?)
  ON CONFLICT(app_id, key) DO UPDATE SET value = excluded.value
`

type SetAppEnvVarParams struct {
	AppID int64  `json:"app_id"`
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetAppEnvVar(ctx context.Context, arg SetAppEnvVarParams) error {
	_, err := q.db.ExecContext(ctx, setAppEnvVar, arg.AppID, arg.Key, arg.Value)
	return err
}
