// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package sqlcgen

import (
	"context"
	"time"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (app_id, addon_id, alias, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, app_id, addon_id, alias, created_at
`

type CreateLinkParams struct {
	AppID     int64     `json:"app_id"`
	AddonID   int64     `json:"addon_id"`
	Alias     string    `json:"alias"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink,
		arg.AppID,
		arg.AddonID,
		arg.Alias,
		arg.CreatedAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AddonID,
		&i.Alias,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links WHERE app_id = ? AND addon_id = ?
`

type DeleteLinkParams struct {
	AppID   int64 `json:"app_id"`
	AddonID int64 `json:"addon_id"`
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) error {
	_, err := q.db.ExecContext(ctx, deleteLink, arg.AppID, arg.AddonID)
	return err
}

const deleteLinksForAddon = `-- name: DeleteLinksForAddon :exec
DELETE FROM links WHERE addon_id = ?
`

func (q *Queries) DeleteLinksForAddon(ctx context.Context, addonID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLinksForAddon, addonID)
	return err
}

const deleteLinksForApp = `-- name: DeleteLinksForApp :exec
DELETE FROM links WHERE app_id = ?
`

func (q *Queries) DeleteLinksForApp(ctx context.Context, appID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLinksForApp, appID)
	return err
}

const getLink = `-- name: GetLink :one
SELECT id, app_id, addon_id, alias, created_at FROM links WHERE app_id = ? AND addon_id = ?
`

type GetLinkParams struct {
	AppID   int64 `json:"app_id"`
	AddonID int64 `json:"addon_id"`
}

func (q *Queries) GetLink(ctx context.Context, arg GetLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLink, arg.AppID, arg.AddonID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AddonID,
		&i.Alias,
		&i.CreatedAt,
	)
	return i, err
}

const listLinksForAddon = `-- name: ListLinksForAddon :many
SELECT l.id, l.alias,
       a.id AS app_id, a.name AS app_name, a.current_deploy_id
  FROM links l
  INNER JOIN apps a ON a.id = l.app_id
  WHERE l.addon_id = ? AND a.deleted_at IS NULL
  ORDER BY l.id
`

type ListLinksForAddonRow struct {
	ID              int64  `json:"id"`
	Alias           string `json:"alias"`
	AppID           int64  `json:"app_id"`
	AppName         string `json:"app_name"`
	CurrentDeployID *int64 `json:"current_deploy_id"`
}

func (q *Queries) ListLinksForAddon(ctx context.Context, addonID int64) ([]ListLinksForAddonRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinksForAddon, addonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksForAddonRow
	for rows.Next() {
		var i ListLinksForAddonRow
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.AppID,
			&i.AppName,
			&i.CurrentDeployID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksForApp = `-- name: ListLinksForApp :many
SELECT l.id, l.alias,
       s.id AS addon_id, s.name AS addon_name, s.engine, s.version, s.password
  FROM links l
  INNER JOIN addons s ON s.id = l.addon_id
  WHERE l.app_id = ? AND s.deleted_at IS NULL
  ORDER BY l.id
`

type ListLinksForAppRow struct {
	ID        int64  `json:"id"`
	Alias     string `json:"alias"`
	AddonID   int64  `json:"addon_id"`
	AddonName string `json:"addon_name"`
	Engine    string `json:"engine"`
	Version   string `json:"version"`
	Password  string `json:"password"`
}

func (q *Queries) ListLinksForApp(ctx context.Context, appID int64) ([]ListLinksForAppRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinksForApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksForAppRow
	for rows.Next() {
		var i ListLinksForAppRow
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.AddonID,
			&i.AddonName,
			&i.Engine,
			&i.Version,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
