// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type Addon struct {
	ID            int64      `json:"id"`
	Name          string     `json:"name"`
	Engine        string     `json:"engine"`
	Version       string     `json:"version"`
	CpuLimit      float64    `json:"cpu_limit"`
	MemoryLimitMb int64      `json:"memory_limit_mb"`
	Password      string     `json:"password"`
	Status        string     `json:"status"`
	ContainerName *string    `json:"container_name"`
	CreatedAt     time.Time  `json:"created_at"`
	DeletedAt     *time.Time `json:"deleted_at"`
	Exposed       bool       `json:"exposed"`
	HostPort      int64      `json:"host_port"`
}

type AddonOwner struct {
	AddonID int64 `json:"addon_id"`
	UserID  int64 `json:"user_id"`
}

type App struct {
	ID               int64      `json:"id"`
	Name             string     `json:"name"`
	Port             int64      `json:"port"`
	HealthPath       string     `json:"health_path"`
	HealthTimeoutSec int64      `json:"health_timeout_sec"`
	CpuLimit         float64    `json:"cpu_limit"`
	MemoryLimitMb    int64      `json:"memory_limit_mb"`
	CurrentDeployID  *int64     `json:"current_deploy_id"`
	CreatedAt        time.Time  `json:"created_at"`
	DeletedAt        *time.Time `json:"deleted_at"`
}

type AppEnv struct {
	AppID int64  `json:"app_id"`
	Key   string `json:"key"`
	Value string `json:"value"`
}

type AppOwner struct {
	AppID  int64 `json:"app_id"`
	UserID int64 `json:"user_id"`
}

type Deployment struct {
	ID            int64      `json:"id"`
	AppID         int64      `json:"app_id"`
	ImageDigest   string     `json:"image_digest"`
	ImageRef      string     `json:"image_ref"`
	CommitSha     *string    `json:"commit_sha"`
	Ref           *string    `json:"ref"`
	Status        string     `json:"status"`
	FailureReason *string    `json:"failure_reason"`
	TriggeredBy   int64      `json:"triggered_by"`
	ContainerName *string    `json:"container_name"`
	CreatedAt     time.Time  `json:"created_at"`
	FinishedAt    *time.Time `json:"finished_at"`
}

type Link struct {
	ID        int64     `json:"id"`
	AppID     int64     `json:"app_id"`
	AddonID   int64     `json:"addon_id"`
	Alias     string    `json:"alias"`
	CreatedAt time.Time `json:"created_at"`
}

type Token struct {
	ID         int64      `json:"id"`
	TokenHash  string     `json:"token_hash"`
	Kind       string     `json:"kind"`
	UserID     *int64     `json:"user_id"`
	AppID      *int64     `json:"app_id"`
	Name       *string    `json:"name"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
}

type User struct {
	ID        int64      `json:"id"`
	Username  string     `json:"username"`
	IsAdmin   bool       `json:"is_admin"`
	CreatedAt time.Time  `json:"created_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}
