// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlcgen

import (
	"context"
	"time"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (token_hash, kind, user_id, app_id, name, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, token_hash, kind, user_id, app_id, name, created_at, last_used_at, revoked_at
`

type CreateTokenParams struct {
	TokenHash string    `json:"token_hash"`
	Kind      string    `json:"kind"`
	UserID    *int64    `json:"user_id"`
	AppID     *int64    `json:"app_id"`
	Name      *string   `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.TokenHash,
		arg.Kind,
		arg.UserID,
		arg.AppID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Kind,
		&i.UserID,
		&i.AppID,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, token_hash, kind, user_id, app_id, name, created_at, last_used_at, revoked_at FROM tokens WHERE token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByHash, tokenHash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Kind,
		&i.UserID,
		&i.AppID,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, token_hash, kind, user_id, app_id, name, created_at, last_used_at, revoked_at FROM tokens WHERE id = ?
`

func (q *Queries) GetTokenByID(ctx context.Context, id int64) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByID, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Kind,
		&i.UserID,
		&i.AppID,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listDeployTokens = `-- name: ListDeployTokens :many
SELECT id, token_hash, kind, user_id, app_id, name, created_at, last_used_at, revoked_at FROM tokens WHERE app_id = ? AND revoked_at IS NULL ORDER BY id
`

func (q *Queries) ListDeployTokens(ctx context.Context, appID *int64) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listDeployTokens, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.Kind,
			&i.UserID,
			&i.AppID,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTokens = `-- name: ListUserTokens :many
SELECT id, token_hash, kind, user_id, app_id, name, created_at, last_used_at, revoked_at FROM tokens WHERE user_id = ? AND revoked_at IS NULL ORDER BY id
`

func (q *Queries) ListUserTokens(ctx context.Context, userID *int64) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listUserTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.Kind,
			&i.UserID,
			&i.AppID,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE tokens SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL
`

type RevokeTokenParams struct {
	RevokedAt *time.Time `json:"revoked_at"`
	ID        int64      `json:"id"`
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeToken, arg.RevokedAt, arg.ID)
	return err
}

const touchTokenLastUsed = `-- name: TouchTokenLastUsed :exec
UPDATE tokens SET last_used_at = ? WHERE id = ?
`

type TouchTokenLastUsedParams struct {
	LastUsedAt *time.Time `json:"last_used_at"`
	ID         int64      `json:"id"`
}

func (q *Queries) TouchTokenLastUsed(ctx context.Context, arg TouchTokenLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchTokenLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
