#!/usr/bin/env bash
# milo one-line installer.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/callmemhz/milo/main/scripts/bootstrap.sh \
#     | sudo bash
#
# What it does:
#   1. Installs Docker via get.docker.com (skipped if already present)
#   2. Downloads deploy/{docker-compose.yml,Caddyfile,env.example} from this repo
#   3. Prompts for ROOT_DOMAIN, API_DOMAIN, ALIDNS_ACCESS_KEY_ID/SECRET
#   4. Writes .env, runs `docker compose up -d`
#   5. Captures the first-run BOOTSTRAP_ADMIN_TOKEN and prints it
#
# Override behavior with env vars (for unattended installs):
#   ROOT_DOMAIN, API_DOMAIN, ALIDNS_ACCESS_KEY_ID, ALIDNS_ACCESS_KEY_SECRET,
#   GHCR_USER, GHCR_TOKEN
#   CPFS_MOUNTS  (optional; "fs-id=server:/path[;...]" — installs systemd
#                 NFS mount units at /mnt/cpfs/<fs-id>)
#   INSTALL_DIR (default: /opt/milo)
#   MILO_VERSION (default: latest)
#   REF (default: main — branch/tag to fetch deploy assets from)

set -euo pipefail

REPO="callmemhz/milo"
REF="${REF:-main}"
RAW_BASE="https://raw.githubusercontent.com/${REPO}/${REF}"
INSTALL_DIR="${INSTALL_DIR:-/opt/milo}"
VERSION="${MILO_VERSION:-latest}"

log() { printf '\n\033[1;36m==>\033[0m \033[1m%s\033[0m\n' "$*"; }
err() { printf '\033[1;31m!!\033[0m %s\n' "$*" >&2; }

if [ "$(id -u)" -ne 0 ]; then
  err "this script needs root; re-run with: curl ... | sudo bash"
  exit 1
fi

# ────────────────────────────────────────────────────────────────────────
# 1. Docker
# ────────────────────────────────────────────────────────────────────────
if command -v docker >/dev/null && docker version >/dev/null 2>&1; then
  log "Docker already installed: $(docker version --format '{{.Server.Version}}')"
else
  log "Installing Docker via get.docker.com"
  curl -fsSL https://get.docker.com | sh
fi

if ! docker compose version >/dev/null 2>&1; then
  err "docker compose plugin not available; please install 'docker-compose-plugin'"
  exit 1
fi

# ────────────────────────────────────────────────────────────────────────
# 2. Config (interactive unless preset via env)
# ────────────────────────────────────────────────────────────────────────
prompt_var() {
  local var=$1 desc=$2 default=${3:-}
  if [ -n "${!var:-}" ]; then return; fi
  local val=""
  if [ -r /dev/tty ]; then
    if [ -n "$default" ]; then
      read -rp "$desc [$default]: " val < /dev/tty
    else
      read -rp "$desc: " val < /dev/tty
    fi
  fi
  eval "$var=\"\${val:-\$default}\""
}

log "Configuration"
prompt_var ROOT_DOMAIN              "Apps wildcard root (e.g. app.example.com)"
prompt_var API_DOMAIN               "PaaS API hostname (e.g. milo.example.com)"
prompt_var ALIDNS_ACCESS_KEY_ID     "Aliyun RAM AccessKey ID (DNS-only, scoped to your domain)"
prompt_var ALIDNS_ACCESS_KEY_SECRET "Aliyun RAM AccessKey Secret"
prompt_var GHCR_USER                "Fallback GHCR username (leave empty to skip)" ""
if [ -n "${GHCR_USER:-}" ]; then
  prompt_var GHCR_TOKEN             "GHCR token (read:packages PAT)"
fi

if [ -z "${ROOT_DOMAIN:-}" ] || [ -z "${API_DOMAIN:-}" ] \
    || [ -z "${ALIDNS_ACCESS_KEY_ID:-}" ] || [ -z "${ALIDNS_ACCESS_KEY_SECRET:-}" ]; then
  err "ROOT_DOMAIN, API_DOMAIN, ALIDNS_ACCESS_KEY_ID, ALIDNS_ACCESS_KEY_SECRET are required"
  err "(no TTY detected? re-run with these values preset as env vars)"
  exit 1
fi

# ────────────────────────────────────────────────────────────────────────
# 3. Fetch deploy assets
# ────────────────────────────────────────────────────────────────────────
log "Installing to $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
for f in docker-compose.yml Caddyfile Dockerfile.caddy env.example; do
  curl -fsSL "$RAW_BASE/deploy/$f" -o "$f"
done

# ────────────────────────────────────────────────────────────────────────
# 3a. Substitute placeholders in Caddyfile
#     - app.example.com           → $ROOT_DOMAIN
#     - milo.example.com → $API_DOMAIN
#     - labels.3                  → labels.<N>  where N = # labels in
#       ROOT_DOMAIN (so {http.request.host.labels.N} extracts the leftmost
#       subdomain regardless of root depth)
# ────────────────────────────────────────────────────────────────────────
ROOT_LABELS=$(awk -F. '{print NF}' <<<"$ROOT_DOMAIN")
sed -i \
  -e "s|app\.example\.com|${ROOT_DOMAIN}|g" \
  -e "s|milo\.example\.com|${API_DOMAIN}|g" \
  -e "s|labels\.3|labels.${ROOT_LABELS}|g" \
  Caddyfile

# ────────────────────────────────────────────────────────────────────────
# 4. Write .env
# ────────────────────────────────────────────────────────────────────────
log "Writing $INSTALL_DIR/.env"
cat > .env <<EOF
# Generated by bootstrap.sh on $(date -u +%FT%TZ)
ROOT_DOMAIN=$ROOT_DOMAIN
API_DOMAIN=$API_DOMAIN
MILO_NETWORK=milo-net
MILO_VERSION=$VERSION
GHCR_USER=${GHCR_USER:-}
GHCR_TOKEN=${GHCR_TOKEN:-}
ALIDNS_ACCESS_KEY_ID=$ALIDNS_ACCESS_KEY_ID
ALIDNS_ACCESS_KEY_SECRET=$ALIDNS_ACCESS_KEY_SECRET
EOF
chmod 600 .env

# ────────────────────────────────────────────────────────────────────────
# 4a. CPFS mounts (optional)
#     For each entry in CPFS_MOUNTS (semicolon-separated "fs-id=nfs-source"
#     pairs, e.g. "train-fs=abc.cn-hangzhou.nas.aliyuncs.com:/"), install an
#     auto-reconnect systemd mount unit at /mnt/cpfs/<fs-id>. Skipped if
#     CPFS_MOUNTS is empty (interactive mode prompts; preset env skips when
#     unset).
# ────────────────────────────────────────────────────────────────────────
prompt_var CPFS_MOUNTS "CPFS mounts (form: fs-id=server:/path[;...]; empty to skip)" ""

if [ -n "${CPFS_MOUNTS:-}" ]; then
  log "Configuring CPFS mounts"
  if ! command -v mount.nfs >/dev/null 2>&1; then
    if command -v apt-get >/dev/null 2>&1; then
      apt-get update -qq && apt-get install -y -qq nfs-common
    elif command -v yum >/dev/null 2>&1; then
      yum install -y nfs-utils
    else
      err "no apt-get or yum found; install nfs-common/nfs-utils manually before retrying"
      exit 1
    fi
  fi

  IFS=';' read -ra CPFS_PAIRS <<<"$CPFS_MOUNTS"
  for pair in "${CPFS_PAIRS[@]}"; do
    pair="${pair// /}"
    [ -z "$pair" ] && continue
    fs_id="${pair%%=*}"
    src="${pair#*=}"
    if [ -z "$fs_id" ] || [ -z "$src" ] || [ "$fs_id" = "$src" ]; then
      err "CPFS_MOUNTS entry %q malformed (expected fs-id=server:/path)" "$pair"
      exit 1
    fi
    target="/mnt/cpfs/${fs_id}"
    unit_name=$(systemd-escape -p --suffix=mount "$target")
    unit_path="/etc/systemd/system/${unit_name}"

    mkdir -p "$target"
    cat > "$unit_path" <<EOF
[Unit]
Description=Mount CPFS ${fs_id} at ${target}
After=network-online.target
Wants=network-online.target

[Mount]
What=${src}
Where=${target}
Type=nfs
Options=vers=3,nolock,proto=tcp,noresvport,_netdev

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable --now "${unit_name}"
    if mountpoint -q "$target"; then
      printf '   ✓ %s mounted at %s\n' "$fs_id" "$target"
    else
      err "${fs_id}: mount unit started but target %s is not a mountpoint — check 'systemctl status %s'" "$target" "$unit_name"
      exit 1
    fi
  done
fi

# ────────────────────────────────────────────────────────────────────────
# 5. Pull + start
# ────────────────────────────────────────────────────────────────────────
log "Pulling images"
docker compose pull --ignore-buildable
log "Building caddy with alidns plugin"
docker compose build caddy
log "Starting stack"
docker compose up -d

# ────────────────────────────────────────────────────────────────────────
# 6. Capture bootstrap admin token
# ────────────────────────────────────────────────────────────────────────
log "Waiting for BOOTSTRAP_ADMIN_TOKEN (max 60s)"
TOKEN=""
for _ in $(seq 1 60); do
  TOKEN=$(docker compose logs milo-control-plane 2>&1 \
    | grep -oE 'BOOTSTRAP_ADMIN_TOKEN=[A-Za-z0-9_-]+' \
    | head -1 | cut -d= -f2 || true)
  [ -n "$TOKEN" ] && break
  sleep 1
done

cat <<EOF

────────────────────────────────────────────────────────────────────────
Installed at $INSTALL_DIR.

Next steps from your workstation:

  brew install callmemhz/milo/milo

  milo auth login \\
    --endpoint=https://$API_DOMAIN \\
    --token=${TOKEN:-<see below>} \\
    --context-name=prod

  milo auth whoami
EOF

if [ -z "$TOKEN" ]; then
  cat <<EOF

(!) Couldn't auto-capture the token. Read it from:
    docker compose -f $INSTALL_DIR/docker-compose.yml logs milo-control-plane | grep BOOTSTRAP_ADMIN_TOKEN

EOF
else
  cat <<EOF

! Save the token above — it is shown only once.
────────────────────────────────────────────────────────────────────────
EOF
fi
