#!/usr/bin/env bash
# milo-apps-kit one-line installer.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/callmemhz/milo-apps-kit/main/scripts/bootstrap.sh \
#     | sudo bash
#
# What it does:
#   1. Installs Docker via get.docker.com (skipped if already present)
#   2. Downloads deploy/{docker-compose.yml,Caddyfile,env.example} from this repo
#   3. Prompts for ROOT_DOMAIN, API_DOMAIN, ALIDNS_ACCESS_KEY_ID/SECRET
#   4. Writes .env, runs `docker compose up -d`
#   5. Captures the first-run BOOTSTRAP_ADMIN_TOKEN and prints it
#
# Override behavior with env vars (for unattended installs):
#   ROOT_DOMAIN, API_DOMAIN, ALIDNS_ACCESS_KEY_ID, ALIDNS_ACCESS_KEY_SECRET,
#   GHCR_USER, GHCR_TOKEN
#   INSTALL_DIR (default: /opt/milo-apps-kit)
#   MILO_APPS_KIT_VERSION (default: latest)
#   REF (default: main — branch/tag to fetch deploy assets from)

set -euo pipefail

REPO="callmemhz/milo-apps-kit"
REF="${REF:-main}"
RAW_BASE="https://raw.githubusercontent.com/${REPO}/${REF}"
INSTALL_DIR="${INSTALL_DIR:-/opt/milo-apps-kit}"
VERSION="${MILO_APPS_KIT_VERSION:-latest}"

log() { printf '\n\033[1;36m==>\033[0m \033[1m%s\033[0m\n' "$*"; }
err() { printf '\033[1;31m!!\033[0m %s\n' "$*" >&2; }

if [ "$(id -u)" -ne 0 ]; then
  err "this script needs root; re-run with: curl ... | sudo bash"
  exit 1
fi

# ────────────────────────────────────────────────────────────────────────
# 1. Docker
# ────────────────────────────────────────────────────────────────────────
if command -v docker >/dev/null && docker version >/dev/null 2>&1; then
  log "Docker already installed: $(docker version --format '{{.Server.Version}}')"
else
  log "Installing Docker via get.docker.com"
  curl -fsSL https://get.docker.com | sh
fi

if ! docker compose version >/dev/null 2>&1; then
  err "docker compose plugin not available; please install 'docker-compose-plugin'"
  exit 1
fi

# ────────────────────────────────────────────────────────────────────────
# 2. Config (interactive unless preset via env)
# ────────────────────────────────────────────────────────────────────────
prompt_var() {
  local var=$1 desc=$2 default=${3:-}
  if [ -n "${!var:-}" ]; then return; fi
  local val=""
  if [ -r /dev/tty ]; then
    if [ -n "$default" ]; then
      read -rp "$desc [$default]: " val < /dev/tty
    else
      read -rp "$desc: " val < /dev/tty
    fi
  fi
  eval "$var=\"\${val:-\$default}\""
}

log "Configuration"
prompt_var ROOT_DOMAIN              "Apps wildcard root (e.g. app.example.com)"
prompt_var API_DOMAIN               "PaaS API hostname (e.g. milo-apps-kit.example.com)"
prompt_var ALIDNS_ACCESS_KEY_ID     "Aliyun RAM AccessKey ID (DNS-only, scoped to your domain)"
prompt_var ALIDNS_ACCESS_KEY_SECRET "Aliyun RAM AccessKey Secret"
prompt_var GHCR_USER                "Fallback GHCR username (leave empty to skip)" ""
if [ -n "${GHCR_USER:-}" ]; then
  prompt_var GHCR_TOKEN             "GHCR token (read:packages PAT)"
fi

if [ -z "${ROOT_DOMAIN:-}" ] || [ -z "${API_DOMAIN:-}" ] \
    || [ -z "${ALIDNS_ACCESS_KEY_ID:-}" ] || [ -z "${ALIDNS_ACCESS_KEY_SECRET:-}" ]; then
  err "ROOT_DOMAIN, API_DOMAIN, ALIDNS_ACCESS_KEY_ID, ALIDNS_ACCESS_KEY_SECRET are required"
  err "(no TTY detected? re-run with these values preset as env vars)"
  exit 1
fi

# ────────────────────────────────────────────────────────────────────────
# 3. Fetch deploy assets
# ────────────────────────────────────────────────────────────────────────
log "Installing to $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
for f in docker-compose.yml Caddyfile Dockerfile.caddy env.example; do
  curl -fsSL "$RAW_BASE/deploy/$f" -o "$f"
done

# ────────────────────────────────────────────────────────────────────────
# 3a. Substitute placeholders in Caddyfile
#     - app.example.com           → $ROOT_DOMAIN
#     - milo-apps-kit.example.com → $API_DOMAIN
#     - labels.3                  → labels.<N>  where N = # labels in
#       ROOT_DOMAIN (so {http.request.host.labels.N} extracts the leftmost
#       subdomain regardless of root depth)
# ────────────────────────────────────────────────────────────────────────
ROOT_LABELS=$(awk -F. '{print NF}' <<<"$ROOT_DOMAIN")
sed -i \
  -e "s|app\.example\.com|${ROOT_DOMAIN}|g" \
  -e "s|milo-apps-kit\.example\.com|${API_DOMAIN}|g" \
  -e "s|labels\.3|labels.${ROOT_LABELS}|g" \
  Caddyfile

# ────────────────────────────────────────────────────────────────────────
# 4. Write .env
# ────────────────────────────────────────────────────────────────────────
log "Writing $INSTALL_DIR/.env"
cat > .env <<EOF
# Generated by bootstrap.sh on $(date -u +%FT%TZ)
ROOT_DOMAIN=$ROOT_DOMAIN
API_DOMAIN=$API_DOMAIN
MILO_APPS_KIT_NETWORK=milo-apps-kit-net
MILO_APPS_KIT_VERSION=$VERSION
GHCR_USER=${GHCR_USER:-}
GHCR_TOKEN=${GHCR_TOKEN:-}
ALIDNS_ACCESS_KEY_ID=$ALIDNS_ACCESS_KEY_ID
ALIDNS_ACCESS_KEY_SECRET=$ALIDNS_ACCESS_KEY_SECRET
EOF
chmod 600 .env

# ────────────────────────────────────────────────────────────────────────
# 5. Pull + start
# ────────────────────────────────────────────────────────────────────────
log "Pulling images"
docker compose pull --ignore-buildable
log "Building caddy with alidns plugin"
docker compose build caddy
log "Starting stack"
docker compose up -d

# ────────────────────────────────────────────────────────────────────────
# 6. Capture bootstrap admin token
# ────────────────────────────────────────────────────────────────────────
log "Waiting for BOOTSTRAP_ADMIN_TOKEN (max 60s)"
TOKEN=""
for _ in $(seq 1 60); do
  TOKEN=$(docker compose logs milo-apps-kit-control-plane 2>&1 \
    | grep -oE 'BOOTSTRAP_ADMIN_TOKEN=[A-Za-z0-9_-]+' \
    | head -1 | cut -d= -f2 || true)
  [ -n "$TOKEN" ] && break
  sleep 1
done

cat <<EOF

────────────────────────────────────────────────────────────────────────
Installed at $INSTALL_DIR.

Next steps from your workstation:

  brew install callmemhz/milo-apps-kit/milo-apps-kit

  milo-apps-kit auth login \\
    --endpoint=https://$API_DOMAIN \\
    --token=${TOKEN:-<see below>} \\
    --context-name=prod

  milo-apps-kit auth whoami
EOF

if [ -z "$TOKEN" ]; then
  cat <<EOF

(!) Couldn't auto-capture the token. Read it from:
    docker compose -f $INSTALL_DIR/docker-compose.yml logs milo-apps-kit-control-plane | grep BOOTSTRAP_ADMIN_TOKEN

EOF
else
  cat <<EOF

! Save the token above — it is shown only once.
────────────────────────────────────────────────────────────────────────
EOF
fi
